package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "plan",
    srcs = glob([
        "*.h",
        "*.cc",
    ]),
    deps = [
        "//reap/core",
        "//reap/proto",
    ],
)