cc_binary(
    name = "test",
    srcs = [
        "main.cc",
    ],
    linkopts = [
        "-lm",
    ],
    deps = [
        "//reap/core/geometry",
        "//reap/core/util",
        "//reap/plan",
        "//reap/proto",
    ],
)