package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "geometry",
    srcs = glob([
        "*.h",
        "*.cc",
    ]),
    deps = [
        "//reap/core/util",
        "//reap/proto",
    ],
    alwayslink = 1,
)