package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "core",
    srcs = glob([
        "*.h",
        "*.cc",
    ]),
    deps = [
        "//reap/proto",
        "@cgal",
    ],
)